course/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('course/',views.course_list,name="course"),
    path('my_course',views.my_course_list,name="my_course"),
    path('course_detail/<int:course>/',views.course_detail,name='course_detail'),
    path('material/<int:part>/',views.material,name='material'),
    path('video/<int:part>/',views.video,name='video'),
    path('session/<int:part>/<int:course>',views.session,name='session'),
    path('course_test_list/<int:part>/',views.test_list,name='test_list'),
    path('course_test/<int:test>/',views.test,name='course_test'),
    path('course_view_result/<int:test>/',views.view_result,name='course_view_result'),
    path('course_test_answer/<int:test>/',views.view_answer,name='course_test_answer'),   
    path('course_mains_test/',views.course_mains_test,name='course_mains_test'),
    
    path('course_mains_part_test/<int:part>/',views.course_mains_part_test,name='course_mains_part_test'), 
    
    #path('course_mains_test_detail/<int:course>/',views.course_mains_test_detail,name='course_mains_test_detail'), 
    path('course_mains_test/<int:assignment_id>/',views.course_mains_test,name='course_mains_test'), 
    path('course_mains_test_reslt/<int:assignment_id>/',views.course_mains_test_result,name='course_mains_test_result'),    
    path('course_load_question/',views.load_question,name='course_load_question'),
    path('course_performance/<int:pk>',views.course_performance,name='course_performance'), 
    path('course_schedule/<int:course_id>/',views.schedule,name='course_schedule'),

]

kpriasacademy/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('mcq_test.urls')),
    path('', include('tseries.urls')),
    path('', include('course.urls')),
    path('', include('daily_mcq.urls')),
    path('', include('scholarship.urls')),
    path('', include('subject.urls')),
    path('', include('mains_test_series.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)





course/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from subject.models import Subject
from django.urls import reverse
from django.utils.safestring import mark_safe
from tseries.models import Series
from mains_test_series.models import Mains_Test_Series
from datetime import date


upse_status_options = (('','Choose Current Status of UPSC'),('Registered','Registered'),('Prelims Attempted','Prelims Attempted'),('Prelims Cleared','Prelims Cleared'),('Main Attempted','Main Attempted'),('Main Cleared','Main Cleared'),('Interview  Attempt','Interview  Attempt'),('Rank','Rank'),('all','all'))
test_options=(('','Choose Test Type'),('P','Prelims'),('M','Mains'))


class Batch(models.Model):
    name=models.CharField(max_length=100)

    def __str__(self):
        return self.name


# Create your models here.
class Course(models.Model):
    title=models.CharField(max_length=100)
    description=models.TextField()
    open_date=models.DateTimeField()
    close_date=models.DateTimeField()
    created_by=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='course_created_by')
    moderator=models.ManyToManyField(settings.AUTH_USER_MODEL,blank=True)
    active=models.BooleanField(default=False)
    lesson_plan=models.FileField(null=True,blank=True,upload_to='course',verbose_name="Brochure")
    prelims_test_series=models.ForeignKey(Series,on_delete=models.SET_NULL,null=True,blank=True)
    mains_test_series=models.ForeignKey(Mains_Test_Series,on_delete=models.SET_NULL,null=True,blank=True)


    def __str__(self):
        return self.title


class Part(models.Model):
    title=models.CharField(max_length=30)
    description=models.TextField(null=True,blank=True)
    course=models.ForeignKey(Course,on_delete=models.CASCADE)
    test_type=models.CharField(choices=test_options,max_length=20,null=True,blank=True)

    def __str__(self):
        return self.title

    def part_changeform_link(self):
        if self.id:
            
            changeform_url = reverse(
            'admin:course_part_change', args=(self.id,)
            )
            return mark_safe(u'<a href="%s" target="_blank">View Part</a>' % changeform_url)
        return u''
    part_changeform_link.allow_tags = True
    part_changeform_link.short_description = '' 



class Topic(models.Model):
    name=models.CharField(max_length=30)
    part=models.ForeignKey(Part,on_delete=models.CASCADE)
    subject=models.ForeignKey(Subject,on_delete=models.CASCADE)

    def __str__(self):
        return self.name



    def changeform_link(self):
        if self.id:
            
            changeform_url = reverse(
            'admin:course_topic_change', args=(self.id,)
            )
            return mark_safe(u'<a href="%s" target="_blank">View Topic</a>' % changeform_url)
        return u''
    changeform_link.allow_tags = True
    changeform_link.short_description = ''


'''
class Class_Test(models.Model):
    title=models.CharField(max_length=50,null=True)
    part=models.ForeignKey(Part,on_delete=models.CASCADE)
    description=models.TextField()

    def __str__(self):
        return self.title

    def class_changeform_link(self):
        if self.id:
            
            changeform_url = reverse(
            'admin:course_class_test_change', args=(self.id,)
            )
            return mark_safe(u'<a href="%s" target="_blank">View Class Test</a>' % changeform_url)
        return u''
    class_changeform_link.allow_tags = True
    class_changeform_link.short_description = ''
    
'''

class Live_Sessions(models.Model):
    topic=models.ForeignKey(Topic,on_delete=models.CASCADE)
    title=models.CharField(max_length=50)
    start_date_time=models.DateTimeField()
    end_date_time=models.DateField()
    link=models.URLField(max_length=200)
    password_if_any=models.CharField(max_length=30,blank=True)
    batch=models.ForeignKey(Batch,on_delete=models.CASCADE,null=True)


    class Meta:
        verbose_name="Live Session"    

class Video(models.Model):
    topic=models.ForeignKey(Topic,on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    link =  models.CharField(max_length=255)
    close_date=models.DateField(default=None)
    batch=models.ForeignKey(Batch,on_delete=models.CASCADE,null=True)



    @property
    def date_comparing(self):
        if self.close_date >= date.today():            
            return True
        else:
            return False

    class Meta:
        ordering = ['id']


class Material(models.Model):
    title=models.CharField(max_length=50,null=True)
    topic=models.ForeignKey(Topic,on_delete=models.CASCADE)
    material = models.FileField(upload_to='profile_photo/material')

    class Meta:
        ordering = ['id']


    @property
    def material_url(self):
        if self.material:
            return self.material.url 




    

course/forms.py
from django import forms
from assignment.models import Submission


class SubmissionForm(forms.ModelForm):  
    class Meta:
        model = Submission
        fields = ('sfile',)

mcq_test/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from tseries.models import Series
from account.models import Test_Series_Enrolment
from .models import Test,Question,Response,On_Test
from django.views.generic.detail import SingleObjectMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from .models import Attempt
from datetime import datetime, date, timedelta
import json
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.core.mail import EmailMultiAlternatives
from django.conf import settings
from django.template.loader import render_to_string
from account.views import complete_profile


# Create your views here.
@complete_profile
@login_required(login_url='login') 
def test_series_list(request):    
    series=Series.objects.filter(start_date__lte=date.today(), end_date__gte=date.today(),active=True).order_by('-start_date')       
    return render(request, 'test/test_series_list.html', {'series':series,})


@complete_profile
@login_required(login_url='login')
def test_series_detail(request,series):      
    if Test_Series_Enrolment.objects.filter(series=series,user=request.user).exists() or request.user.groups.filter(name='Instructor').exists():
        test= Test.objects.filter(test_series=series,active="True").order_by('open_date') 
        return render(request, 'test/view_test_series.html', {'test':test,})

    return HttpResponse("You don't have rights to access the test series")


@complete_profile
@login_required(login_url='login') 
def view_instruction(request,test):
    
    if Test_Series_Enrolment.objects.filter(series__test=test,user=request.user,series__test__open_date__lte=datetime.now(),series__test__close_date__gte=datetime.now(),series__test__active="True").exists() or request.user.groups.filter(name='Instructor').exists():
        test=Test.objects.get(id=test)
        return render(request, 'test/view_instruction.html', {'test':test,})

    return HttpResponse("You don't have rights to view the instruction")


@complete_profile
@login_required(login_url='login') 
def test(request,test):

    test_object=Test.objects.get(id=test)
    if Attempt.objects.filter(test=test,user=request.user).exists():
        return HttpResponse("No More attempts allowed")



    if not On_Test.objects.filter(user=request.user).exists():
        On_Test.objects.create(user=request.user,test_id=test,started_time=datetime.now())

    old_one=[]

    current_test=Test.objects.get(id=test)
    old_test=On_Test.objects.get(user=request.user)   
 
    if current_test.id == old_test.test.id:
        then = old_test.started_time
        now = datetime.strptime(datetime.now().strftime('%Y-%m-%d %H:%M:%S'),'%Y-%m-%d %H:%M:%S') 
        diff = (now - then).total_seconds()       
        mins = current_test.duration_in_minutes - ((diff // 60) + 1)
        seconds = 59 - diff % 60


        test_object=Test.objects.get(id=test,test_series__isnull=False)
        questions=list(test_object.question.values_list('id',flat=True))

        question = Question.objects.get(id=questions[0])
  
               
        context={
                'sorted_questions' : questions,
                'question_count' : len(questions),
                'question_no' : 0,
                'question' : question,
                'test':test_object,
                'question_next' : 1,
                'question_prev' : -1,
                'mins':mins,
                'seconds':seconds
            
             }
        return render(request, 'test/test_new.html', context)
    
    elif current_test.id != old_test.test.id:
        return  render(request, 'test/old_test.html', {'old_test':old_test,'current_test':current_test,})
    
    
@login_required(login_url='login') #Authentication   
def testsubmit(request):   

        json_data=json.loads(request.body.decode('utf-8'))    
        data = dict()
        current_user = request.user
        test_id=int(json_data[0]['testid'])  
        if Attempt.objects.filter(user=request.user,test=test_id).exists():
            data['attempted'] = "attempted"
            return JsonResponse(data)  
        test = Test.objects.get(id=test_id)     
        stime=On_Test.objects.get(user=request.user,test=test)           
        start_time=stime.started_time  
        end_time=datetime.now()
       

        if len(json_data)==1 and not 'questionid' in json_data[0]:
            
            Attempt.objects.create(user = current_user, test = test,score = 0,start_date_time=start_time,end_date_time=end_time)
            score=0
            On_Test.objects.filter(user=current_user,test=test).delete()     
        else:
            
            score = Attempt.Create(test_id,current_user,json_data,start_time) 
            
        
        data['score'] = score        
        return JsonResponse(data)
   
@complete_profile
@login_required(login_url='login') 
def view_result(request,test): 
    
    attempt=Attempt.objects.get(test=test,user=request.user)      
    question=Question.objects.filter(test__id=test)   
    today = date.today()
    d1 = today.strftime("%d/%m/%Y")   
    return render(request, 'test/view_result.html', {'attempt':attempt,'question':question,'today':d1})

@complete_profile
@login_required(login_url='login') 
def view_answer(request,test):    
    attempt=Attempt.objects.get(test=test,user=request.user)      
    question=Question.objects.filter(test__id=test)      
    return render(request, 'test/view_answer.html', {'attempt':attempt,'question':question})

 
def delete_on_test(request,test):
    On_Test.objects.filter(user=request.user,test=test).delete()
    data = dict()
    data['status'] = 'done'       
    return JsonResponse(data)
   
@complete_profile
@login_required(login_url='login') 
def view_discussion(request,test): 
    if Attempt.objects.filter(test=test,user=request.user).exists():
        test=Test.objects.get(id=test)      
        return render(request, 'test/view_discussion.html', {'test':test,})

    else:
        return HttpResponse("Attend the test first")




@complete_profile
@login_required(login_url='login') 
def test_completed(request,test): 
    if Attempt.objects.filter(test=test,user=request.user).exists():
        test=Test.objects.get(id=test)      
        return render(request, 'test/test_completed.html', {'test':test,})

    else:
        return HttpResponse("Attend the test first")

@complete_profile
@login_required(login_url='login')
def load_question(request):
    data = dict()
    no = int(request.GET.get('question_no'))
    print(no)
    test = request.GET.get('test')
    if str(test) in request.session:
                
        #get test questions
        test_object=Test.objects.get(id=test)
        
        question = Question.objects.get(id=request.session[str(test)][no])
               
        context={
            
            'question' : question,
            'test':test_object,
            'question_no': no,
            
            
        }
        data['question'] = render_to_string('test/test_fly.html', context) 
        data['question_no'] = no
        data['question_id'] = question.id
        data['question_count'] = len(request.session[str(test)])
    else:
        data['error'] = "Something went Wrong"
    return JsonResponse(data)

def ajax_load_questions(request):
    data = dict()
    questions=request.GET.get('question')
    questions=request.GET.get('question')
    questions=json.loads(questions)
    questions = [x.strip() for x in questions.split(',')]
    questions=Question.objects.filter(id__in=questions)

    context={            
            'questions' : questions,      
            
        }
    data['questions'] = render_to_string('admin/question_fly.html', context) 

    return JsonResponse(data)

templates/course/course_mains_test.html
{% extends 'base.html' %}
{% load enrollment_tags %}

{% block content %}

{% load static %}
<div class="subheader py-2 py-lg-6 subheader-solid" id="kt_subheader">
    <div class="container-fluid d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
        <!--begin::Info-->
        <div class="d-flex align-items-center flex-wrap mr-1">
            <!--begin::Page Heading-->
            <div class="d-flex align-items-baseline flex-wrap mr-5">
                <!--begin::Page Title-->
                <h5 class="text-dark font-weight-bold my-1 mr-5">Course</h5>
                <!--end::Page Title-->
                <!--begin::Breadcrumb-->
                <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
                    <li class="breadcrumb-item">
                        <a href="{% url 'home'  %}" class="text-muted">Home</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="{% url 'course' %}" class="text-muted"> Courses</a>
                    </li>
                  
                </ul>
                <!--end::Breadcrumb-->
            </div>
            <!--end::Page Heading-->
        </div>
        <!--end::Info-->
        <!--begin::Toolbar-->
       
    </div>
</div>

    <!--begin::Entry-->
    <div class="d-flex flex-column-fluid mt-5">
        <!--begin::Container-->
        <div class="container">
            <div class="row">

                {% for course in course %}
                <div class="col-lg-6">
                    <!--begin::Mixed Widget 14-->
                    <div class="card card-custom card-stretch gutter-b">
                        <!--begin::Header-->
                        <div class="card-header border-0 pt-5">
                            <h3 class="card-title font-weight-bolder">{{course}}</h3>
                            
                        </div>
                        <!--end::Header-->
                        <!--begin::Body-->
                        <div class="card-body d-flex flex-column">
                            
                            <div class="pt-5 align-items-center">
                                
                                <p class="text-center"><img src="{%static 'assets/media/pic.png' %}" alt="" ></p>
                                <p class="text-center font-weight-normal font-size-lg pb-7" style="text-align: center;margin: auto;">
                                    {{course.description|safe}}
                                </p>
                                 
                                {% if course.id|check_course_enrollment:request.user  %}

                                  {% if course.lesson_plan %}
                                    <div class="text-center">
                                        <a href="{% url 'course_mains_test_detail' course.id %}" class="btn  btn-success btn-shadow-hover font-weight-bolder  py-3">View Course Detail</a>
                                        <a href="media/{{course.lesson_plan}}" download class="btn  btn-success btn-shadow-hover font-weight-bolder  py-3">Download Course Plan</a>
                                    </div>
                                {% else %}
                                <a href="{% url 'course_mains_test_detail' course.id %}" class="btn  btn-success btn-shadow-hover font-weight-bolder w-100  py-3">View Course Detail</a>
                                {% endif %}

                                {% else %}

                                <h4 class="card-title font-weight-bolder text-center"> Not Enrolled </h4>
                      
                                {% endif %}

                     

                            </div>
                        </div>
                        <!--end::Body-->
                    </div>
                    <!--end::Mixed Widget 14-->
                </div>
                {% endfor %}
                
            </div>
        </div>
        <!--end::Container-->
    </div>
    <!--end::Entry-->


{% endblock %}

templates/course/material.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container">
  

   <div class="subheader py-2 py-lg-6 subheader-solid" id="kt_subheader">
    <div class="container-fluid d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
        <!--begin::Info-->
        <div class="d-flex align-items-center flex-wrap mr-1">
            <!--begin::Page Heading-->
            <div class="d-flex align-items-baseline flex-wrap mr-5">
                <!--begin::Page Title-->
                <h5 class="text-dark font-weight-bold my-1 mr-5">Course</h5>
                <!--end::Page Title-->
                <!--begin::Breadcrumb-->
                <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
                  <li class="breadcrumb-item">
                      <a href="{% url 'home'  %}" class="text-muted">Home</a>
                  </li>
                  <li class="breadcrumb-item">                        
                    <a href="{% url 'course'  %}" class="text-muted"> Course</a>                    
                  </li>
                  <li class="breadcrumb-item">                           
                    {% with topics|first as first_topic %}                      
                      {% if first_topic %}                      											
                           <a href="{% url 'course_detail' first_topic.part.course.id  %}" class="text-muted">{{first_topic.part.course}} </a>
                      {% endif %}
                    {% endwith %}                  
                 </li>

                  <li class="breadcrumb-item">
                    <a href="#" class="text-muted"> Material</a>
                </li>
              </ul>
                <!--end::Breadcrumb-->
            </div>
            <!--end::Page Heading-->
        </div>
        <!--end::Info-->
    </div>
</div>
<br>
<h3>Materials</h3>

   {% for topic in topics %}
       <button class="collapsible mb-1">{{topic}} - {{topic.subject}}</button>
       <div class="material_content">
           <br>
         <ul>
             {% for material in topic.material_set.all %}
       
             <li  style="list-style-type: none;">

              <div class="row pl-3">  
                <h3>                                                       
                <i class="text-dark-50 flaticon-download"></i>  &nbsp; &nbsp;
                      
                <a style="float-right" href="{{material.material.url}}" download>
                  {{material.title}}
                </a>    

              </h3>

            </div>


             {% endfor %}

          </ul>

        </div>
   {% empty %}     
        <h3>No Materils Available </h3>
   {% endfor %}


</div>
<script>
    var coll = document.getElementsByClassName("collapsible");
    var i;
    
    for (i = 0; i < coll.length; i++) {
      coll[i].addEventListener("click", function() {
        this.classList.toggle("active");
        var content = this.nextElementSibling;
        if (content.style.maxHeight){
          content.style.maxHeight = null;
        } else {
          content.style.maxHeight = content.scrollHeight + "px";
        } 
      });
    }
    </script>

{% endblock %}

templates/course/video.html
{% extends 'base.html' %}
{% load static %}
{% load batch_filter %}
{% block content %}

<div class="container">

  <div class="subheader py-2 py-lg-6 subheader-solid" id="kt_subheader">
    <div class="container-fluid d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
        <!--begin::Info-->
        <div class="d-flex align-items-center flex-wrap mr-1">
            <!--begin::Page Heading-->
            <div class="d-flex align-items-baseline flex-wrap mr-5">
                <!--begin::Page Title-->
                <h5 class="text-dark font-weight-bold my-1 mr-5">Course</h5>
                <!--end::Page Title-->
                <!--begin::Breadcrumb-->
                <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
                  <li class="breadcrumb-item">
                      <a href="{% url 'home'  %}" class="text-muted">Home</a>
                  </li>
                  <li class="breadcrumb-item">                        
                    <a href="{% url 'course'  %}" class="text-muted"> Course</a>                    
                  </li>
                  <li class="breadcrumb-item">                           
                    {% with topics|first as first_topic %}                      
                      {% if first_topic %}                      											
                           <a href="{% url 'course_detail' first_topic.part.course.id  %}" class="text-muted">{{first_topic.part.course}} </a>
                      {% endif %}
                    {% endwith %}                  
                 </li>
                  <li class="breadcrumb-item">
                    <a href="#" class="text-muted"> Video</a>
                </li>
              </ul>
                <!--end::Breadcrumb-->
            </div>
            <!--end::Page Heading-->
        </div>
        <!--end::Info-->
    </div>
</div>
<br>


   <h3>Videos</h3>

   <div class="row">
      <div class="col-sm-8"> 

        <p id="watchvideo"></p>
        <div class="kt-pricing-1__item col-lg-12 mt-5">                                                                                     
            
            
            
               <div  style="width: 640px; height: 480px; position: relative;">
                {% comment %}
                 <iframe src="" sandbox="allow-forms allow-pointer-lock allow-same-origin allow-scripts allow-top-navigation"  width="640" height="480" frameborder="0" scrolling="no" seamless="">
                 </iframe>
                 {% endcomment %}

                 <iframe width="640" height="480" src="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>

                 </iframe>
                 
            <div style="width: 80px; height: 80px; position: absolute; opacity: 0; right: 0px; top: 0px;"> </div>
      </div>
            
                                                                        
        </div>


      </div>
      <div class="col-sm-4 mt-4" style="overflow-y: scroll !important;height:480px;">

       {% for topic in topics %}

       <button class="collapsible mb-1">{{topic}} - {{topic.subject}}</button>
       <div class="material_content">
           <br>
         <ul>
             {% for video in topic.video_set.all %}                                                               
               
                {% get_batch video.topic.part.course.id user as course_enrolment %}

                  {% if course_enrolment.batch == video.batch %}                                  
                   
                      {% if video.date_comparing %}  
                         <li class="w-100 " style="list-style-type: none;">              
                          <div class="row pl-3 pt-3 ">             
                            <h3 class="text-dark-50 icon-xl  far fa-play-circle"> <a style="font-size:1.6rem;font-weight:bold;" class="video_list" href="#" data_link="{{video.link}}?ecver=1"> {{video.title}} </a></h3>
                          </div>
              
                        </li>
                      {% elif course_enrolment.is_lateral %}    
                         <li class="w-100 " style="list-style-type: none;">              
                          <div class="row pl-3 pt-3 ">
                            <h3 class="text-dark-50 icon-xl  far fa-play-circle"> <a style="font-size:1.6rem;font-weight:bold;" class="video_list" href="#" data_link="{{video.link}}?ecver=1"> {{video.title}} </a></h3>
                          </div>
              
                        </li>
                      {% endif %}
                     
                  {% endif %}
                        
             {% endfor %}

          </ul>

        </div>
        {% empty %}

           NO Videos Available for this Part
        

       {% endfor %}

      </div>
    
  </div>


</div>


<script>
    var coll = document.getElementsByClassName("collapsible");
    var i;
    
    for (i = 0; i < coll.length; i++) {
      coll[i].addEventListener("click", function() {
        this.classList.toggle("active");
        var content = this.nextElementSibling;
        if (content.style.maxHeight){
          content.style.maxHeight = null;
        } else {
          content.style.maxHeight = content.scrollHeight + "px";
        } 
      });
    }
    </script>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script>


function getYouTubeVideoId(url) {
  const urlParams = new URLSearchParams(new URL(url).search); // Create URLSearchParams object from the query string
  return urlParams.get('v'); // Extract the 'v' parameter, which is the YouTube video ID
}

function cleanGoogleDriveUrl(url) {
    // Find the position of `/view` in the URL
    const viewIndex = url.indexOf("/view");
    
    // If `/view` is found, return the URL up to that point
    if (viewIndex !== -1) {
        return url.substring(0, viewIndex);  // Returns the URL up to /view
    }
    
    // If `/view` is not found, return the original URL
    return url;
}


    $(document).ready(function(){
        var link = $(".video_list:first").attr('data_link');  
        
        
        if(link.includes("drive.google.com"))
        {
            var url = cleanGoogleDriveUrl(link);
            var link = url + "/preview";

        }
        else if(link.includes("www.youtube.com"))
        {
          var video_id = getYouTubeVideoId(link);
          //var res = link.replace("view?ecver=1", 'preview');
          //var link = res;  
          var link = "https://www.youtube.com/embed/" + video_id ;

        }

       


        $('iframe').attr("src", link);
        $(".video_list:first").css('color','#010142');                                  

        $(".video_list").click(function(e){
            e.preventDefault();
            var link = $(this).attr('data_link');
           
              
          if(link.includes("drive.google.com"))
          {
            var url = cleanGoogleDriveUrl(link);
            var link = url + "/preview";

          }
          else if(link.includes("www.youtube.com"))
         {
          var video_id = getYouTubeVideoId(link);
          //var res = link.replace("view?ecver=1", 'preview');
          //var link = res;  
          var link = "https://www.youtube.com/embed/" + video_id ;

        }

                                             
            $('iframe').attr("src", link);
            $(".video_list").css('color','#7b7c84');
            $(this).css('color','black');
            $('#watchvideo')[0].scrollIntoView(true);                                         
                                                
            });

    });

  

</script>                               
                                




{% endblock %}